config/routes.rb
Rails.application.routes.draw do
  resources :band_members
  resources :songs
  resources :genres
  resources :artists

  root 'artists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/band_member.rb
class BandMember < ApplicationRecord

  belongs_to :artist

end

app/controllers/band_members_controller.rb
class BandMembersController < ApplicationController
  before_action :set_band_member, only: [:show, :edit, :update, :destroy]

  # GET /band_members
  # GET /band_members.json
  def index
    @band_members = BandMember.all
  end

  # GET /band_members/1
  # GET /band_members/1.json
  def show
  end

  # GET /band_members/new
  def new
    @band_member = BandMember.new
    @artists = Artist.all
  end

  # GET /band_members/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /band_members
  # POST /band_members.json
  def create
    @band_member = BandMember.new(band_member_params)

    respond_to do |format|
      if @band_member.save
        format.html { redirect_to @band_member, notice: 'Band member was successfully created.' }
        format.json { render :show, status: :created, location: @band_member }
      else
        format.html { render :new }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /band_members/1
  # PATCH/PUT /band_members/1.json
  def update
    respond_to do |format|
      if @band_member.update(band_member_params)
        format.html { redirect_to @band_member, notice: 'Band member was successfully updated.' }
        format.json { render :show, status: :ok, location: @band_member }
      else
        format.html { render :edit }
        format.json { render json: @band_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /band_members/1
  # DELETE /band_members/1.json
  def destroy
    @band_member.destroy
    respond_to do |format|
      format.html { redirect_to band_members_url, notice: 'Band member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band_member
      @band_member = BandMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_member_params
      params.require(:band_member).permit(:name, :instrument, :artist_id)
    end
end

app/helpers/band_members_helper.rb
module BandMembersHelper
end

app/views/band_members/_form.html.erb
<%= form_with(model: band_member, local: true) do |form| %>
  <% if band_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(band_member.errors.count, "error") %> prohibited this band_member from being saved:</h2>

      <ul>
      <% band_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :instrument %>
    <%= form.text_field :instrument %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.collection_select :artist_id, @artists, :id, :name, id: :song_artist_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/band_members/edit.html.erb
<h1>Editing Band Member</h1>

<%= render 'form', band_member: @band_member %>

<%= link_to 'Show', @band_member %> |
<%= link_to 'Back', band_members_path %>

app/views/band_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Band Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instrument</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @band_members.each do |band_member| %>
      <tr>
        <td><%= band_member.name %></td>
        <td><%= band_member.instrument %></td>
        <td><%= band_member.artist.name %></td>
        <td><%= link_to 'Show', band_member %></td>
        <td><%= link_to 'Edit', edit_band_member_path(band_member) %></td>
        <td><%= link_to 'Destroy', band_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band Member', new_band_member_path %>

app/views/band_members/new.html.erb
<h1>New Band Member</h1>

<%= render 'form', band_member: @band_member %>

<%= link_to 'Back', band_members_path %>

app/views/band_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band_member.name %>
</p>

<p>
  <strong>Instrument:</strong>
  <%= @band_member.instrument %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @band_member.artist_id %>
</p>

<%= link_to 'Edit', edit_band_member_path(@band_member) %> |
<%= link_to 'Back', band_members_path %>